### ISSUE TITLE
List is incomplete in GUI

### ISSUE THREAD

**Issue by jagadeesh-sudhakaraiah** [calexandru2018/protonvpn-linux-gui#101]
On the first install everything was fine. After few days, countries list seems incomplete. I can connect to the countries that are not listed on the GUI via CLI. List doesn't extended beyond Norway. Everything else works great. Please let me know if additional details are required.

OS: Ubuntu 20.04
Kernel: 5.4.0-42-generic
pip version: 20.0.2
python3 version: 3.8.2

**Comment by calexandru2018** [comment]
Hi @jagadeesh-sudhakaraiah 

Thank you for opening this issue. Could you please edit your post and provide the necessary information as per **Issue: Bug report** template ? Also, please attach some screenshots if possible.

**Comment by jagadeesh-sudhakaraiah** [comment]
**Describe the bug**
ProtonVPN country list is incomplete in GUI.

**To Reproduce**
I'm not sure as to what caused the reduction of the list. 
Steps to reproduce the behavior:
1. Go to ProtonVPN GUI client.
2. Scroll down till the end.
3. End of the list is Norway.

**Screenshots**
![protonvpn_gui](https://user-images.githubusercontent.com/9626059/91595585-c53d0000-e931-11ea-874a-4eb2c787d148.png)
Even the search doesn't include all correct results,
![proton_vpn_gui_3](https://user-images.githubusercontent.com/9626059/91607307-b100ff00-e941-11ea-8412-1b60e60257ed.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04 LTS (5.4.0-42-generic)
 - pip version: 20.0.2
 - python3 version: 3.8.2

**Additional context**
Connection to servers not listed in GUI is still possible and the status is correctly displayed both in GUI and tray if the tunnel is established via CLI. Please let me know if additional details are required.

**Comment by calexandru2018** [comment]
Thank you for the update @jagadeesh-sudhakaraiah 

Yes indeed it is a strange behavior and I was also able to replicate this. I'll look closer into this and see if I find what causes this unexpected behavior.

**Comment by jagadeesh-sudhakaraiah** [comment]
Oh cool. Thanks for looking into it. Please let me know if any additional information is required.

**Comment by geodimm** [comment]
Hi @jagadeesh-sudhakaraiah ,

I think I know what might be causing this. Upon executing `protonvpn-gui` I'm getting the following error:

```sh
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/linux_gui/presenters/dashboard_presenter.py", line 384, in populate_server_list
    flag = GdkPixbuf.Pixbuf.new_from_file_at_size(self.dashboard_service.get_flag_path(country), 15,15)
gi.repository.GLib.Error: g-file-error-quark: Failed to open file “/usr/local/lib/python3.8/dist-packages/linux_gui/resources/img/flags/small/Peru.png”: No such file or directory (4)
```

and the list of countries is incomplete.

As a temporary workaround, I did 

```sh
sudo cp /usr/local/lib/python3.8/dist-packages/linux_gui/resources/img/flags/small/Unknown.png \
    /usr/local/lib/python3.8/dist-packages/linux_gui/resources/img/flags/small/Peru.png
```

and it's now displaying all countries :) Hope that helps!

**Comment by PeterDaveHello** [comment]
There are **200** jpg images for flags under [linux_gui/resources/img/flags/large](https://github.com/ProtonVPN/linux-gui/tree/master/linux_gui/resources/img/flags/large), but there are only **81** png images for flags under [linux_gui/resources/img/flags/small](https://github.com/ProtonVPN/linux-gui/tree/master/linux_gui/resources/img/flags/small), which is very interesting. Another interesting part is about the file name: small images is using country name, but large images is using country code.

**Comment by PeterDaveHello** [comment]
Also found another inconsistency: there are 250 countries in [**linux-cli**'s country_codes.py](https://github.com/ProtonVPN/linux-cli/blob/master/protonvpn_cli/country_codes.py), but there are only 200 jpg images for flags under [linux_gui/resources/img/flags/large](https://github.com/ProtonVPN/linux-gui/tree/master/linux_gui/resources/img/flags/large?rgh-link-date=2020-09-28T13%3A48%3A11Z).

**Comment by Papigoe** [comment]
> Hi @jagadeesh-sudhakaraiah ,
> 
> I think I know what might be causing this. Upon executing `protonvpn-gui` I'm getting the following error:
> 
> ```shell
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.8/dist-packages/linux_gui/presenters/dashboard_presenter.py", line 384, in populate_server_list
>     flag = GdkPixbuf.Pixbuf.new_from_file_at_size(self.dashboard_service.get_flag_path(country), 15,15)
> gi.repository.GLib.Error: g-file-error-quark: Failed to open file “/usr/local/lib/python3.8/dist-packages/linux_gui/resources/img/flags/small/Peru.png”: No such file or directory (4)
> ```
> 
> and the list of countries is incomplete.
> 
> As a temporary workaround, I did
> 
> ```shell
> sudo cp /usr/local/lib/python3.8/dist-packages/linux_gui/resources/img/flags/small/Unknown.png \
>     /usr/local/lib/python3.8/dist-packages/linux_gui/resources/img/flags/small/Peru.png
> ```
> 
> and it's now displaying all countries :) Hope that helps!

Upon executing your workaround, I got this:
cp: cannot stat '/usr/local/lib/python3.8/dist-packages/linux_gui/resources/img/flags/small/Unknown.png': No such file or directory

**Comment by atmin** [comment]
@Papigoe most probably your Python version is different than example given. Type `python3 --version`. You'll get something like `Python 3.6.9`. Replace both `python3.8` occurrences in the `cp` paths with `python3.6` (according to your actual version major.minor).

Or go to that directory in one command and copy file in another:
```
cd /usr/local/lib/python`python3 --version | grep -oE '3\..'`/dist-packages/linux_gui/resources/img/flags/small
sudo cp Unknown.png Peru.png
```

**Comment by Papigoe** [comment]
I don't know how to do that, so I'll either just stick with the countries I can see, or just use CLI version. For the record, I'm using Python 3.8.5. Thank you for your response!

[keithcrestcolour.jpg][Keith Roebuck.png]﻿
𝓢𝓬𝓸𝓽𝓽 𝓔𝓵𝓵𝓲𝓼 𝓣𝓪𝔂𝓵𝓸𝓻-𝓗𝓪𝓻𝓿𝓮𝔂

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by geodimm** [comment]
@Papigoe 

You could also try something like

```sh
sudo find /usr/local/lib -name linux_gui -type d
```

You should get the first part of the path.

**Comment by mikewesten** [comment]
Ditto. I am only seeing A through N listed in the GUI. The last available country is Norway. Using the terminal is the only way to access O through Z.

**Comment by jagadeesh-sudhakaraiah** [comment]
Looks like the issue is fixed in the latest commit. Closing the issue.

**Comment by SirLaffalot** [comment]
If you have image magick, then

sudo convert /usr/lib/python3.9/site-packages/linux_gui/resources/img/flags/large/pe.jpg -resize 720x720 /usr/lib/python3.9/site-packages/linux_gui/resources/img/flags/small/Peru.png

fixes it

**Comment by Papigoe** [comment]
> If you have image magick, then
> 
> sudo convert /usr/lib/python3.9/site-packages/linux_gui/resources/img/flags/large/pe.jpg -resize 720x720 /usr/lib/python3.9/site-packages/linux_gui/resources/img/flags/small/Peru.png
> 
> fixes it

Worked a treat!  Thanks to all of you for your help.

**Comment by cbdejavu** [comment]
> If you have image magick, then
> 
> sudo convert /usr/lib/python3.9/site-packages/linux_gui/resources/img/flags/large/pe.jpg -resize 720x720 /usr/lib/python3.9/site-packages/linux_gui/resources/img/flags/small/Peru.png
> 
> fixes it

This fixed it for me as well. so is the issue something that should be reported upstream to the python project?  Is the problem because the python project didn't provide the small country flag for peru?

**Comment by calexandru2018** [comment]
@cbdejavu this is an issue with a missing flag. This project will no longer receive updates as the official GUI for the official CLI is currently being worked on.
