### ISSUE TITLE
Import error: cannot import name

### ISSUE THREAD

**Issue by shawndfernandes** [calexandru2018/protonvpn-linux-gui#118]
**Describe the bug**

protonvpn-gui does not start, ubuntu 20 LTS.

**To Reproduce**
run protonvpn-gui on the Terminal

**Expected behavior**
protonvpn-gui should open

**Actual Behavior**
protonvpn-gui shows error

**Screenshots**
Attached

**Desktop (please complete the following information):**
 - OS: Ubuntu 20

**Additional context**
Traceback (most recent call last):
  File "/home/<username>/.local/bin/protonvpn-gui", line 5, in <module>
    from linux_gui.protonvpn_gui import init
  File "/home/<username>/.local/lib/python3.8/site-packages/linux_gui/protonvpn_gui.py", line 6, in <module>
    from protonvpn_cli.constants import CONFIG_FILE, CONFIG_DIR #noqa
ImportError: cannot import name 'CONFIG_FILE' from 'protonvpn_cli.constants' (/usr/lib/python3/dist-packages/protonvpn_cli/constants.py)
![ProtonVPn-UI-Error](https://user-images.githubusercontent.com/16843666/107719214-506e4000-6c9d-11eb-95c9-5e150f83a164.png)

**Comment by shawndfernandes** [comment]
Possible resolution

https://github.com/shawndfernandes/ProtonVPN-UI
