### ISSUE TITLE
ModuleNotFoundError: No module named 'protonvpn_cli.utils'

### ISSUE THREAD

**Issue by shawndfernandes** [calexandru2018/protonvpn-linux-gui#119]
**Describe the bug**

protonvpn-tray does not start, ubuntu 20 LTS.

**To Reproduce**
run protonvpn-tray on the Terminal

**Expected behavior**
protonvpn-tray should open

**Actual Behavior**
protonvpn-tray shows error

**Screenshots**
Attached

**Desktop (please complete the following information):**
 - OS: Ubuntu 20

**Additional Context**
Traceback (most recent call last):
  File "/home/shawn/.local/bin/protonvpn-tray", line 5, in <module>
    from linux_gui.indicator import ProtonVPNIndicator
  File "/home/shawn/.local/lib/python3.8/site-packages/linux_gui/indicator.py", line 7, in <module>
    from protonvpn_cli.utils import (
ModuleNotFoundError: No module named 'protonvpn_cli.utils'

![ProtonVPn-UI-Error](https://user-images.githubusercontent.com/16843666/107719316-90cdbe00-6c9d-11eb-806b-bb4fb67c6b77.png)

**Comment by shawndfernandes** [comment]
Possible resolution

https://github.com/shawndfernandes/ProtonVPN-UI
